server:
   port: 8082
spring:
   datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: tiger
        url: jdbc:mysql://localhost:3306/OrderDB
        username: root    
   jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update           
   application:
      name: ORDER-SERVICE
   config:
      import: optional:configserver:http://localhost:9296
management:
   tracing:
      sampling:
         probability: 1

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry : true
#    service-url: 
#     defalut-zone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}